language: node_js

services:
  - docker

node_js:
  - 8.10.0

cache:
  directories:
    - node_modules

before_install: bash build.sh
before_script: cd src
script: yarn test

notifications:
  email: false
