language: node_js

services:
  - docker

node_js:
  - 8.10.0

cache:
  directories:
    - node_modules

before_install:
  - docker pull p5-replay/build-service
  - docker run --rm -v ./src:/wrk p5-replay/build-service /bin/bash -c "cd /wrk && yarn test"

script:
  - yarn test

notifications:
  email: false
