AWSTemplateFormatVersion: 2010-09-09
Description: p5-replay Continuous Integration pipeline

Parameters:
  ArtifactBucket:
    Type: String
    Description: Name of existing S3 bucket for storing pipeline artifacts
  TemplateBucket:
    Type: String
    Description: Name of existing S3 bucket for storing CloudFormation template artifacts
  GitHubOwner:
    Type: String
    Description: GitHub repository owner
  GitHubRepo:
    Type: String
    Default: p5-replay
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: master
    Description: GitHub repository branch
  GitHubToken:
    Type: String
    Description: GitHub repository OAuth token
    NoEcho: true
  CodePipelineServiceRoleName:
    Type: String
    Description: CodePipeline Service Role name
    Default: AWS-CodePipeline-Service
  StackName:
    Type: String
    Description: Application stack name
    Default: p5-replay
  StagingStackName:
    Type: String
    Description: Staging application stack name
    Default: p5-replay-staging

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${CodePipelineServiceRoleName}"
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                PollForSourceChanges: false
              OutputArtifacts: [Name: Repo]
        - Name: Build
          Actions:
            - Name: Build
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts: [Name: Repo]
              Configuration:
                ProjectName: !Ref Build
              OutputArtifacts: [Name: Package]
        - Name: Staging
          Actions:
            - Name: CreateChangeSet
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              InputArtifacts: [Name: Package]
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: StagingChangeSet
                RoleArn: !ImportValue p5ReplayCFNRole
                StackName: !Ref StagingStackName
                TemplatePath: Package::output.yml
                TemplateConfiguration: Package::configuration-staging.json
              OutputArtifacts: [Name: StagingChangeSet]
            - Name: ExecuteChangeSet
              RunOrder: 2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              InputArtifacts: [Name: StagingChangeSet]
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: StagingChangeSet
                StackName: !Ref StagingStackName
        - Name: Production
          Actions:
            - Name: CreateChangeSet
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              InputArtifacts: [Name: Package]
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: ProdChangeSet
                RoleArn: !ImportValue p5ReplayCFNRole
                StackName: !Ref StackName
                TemplatePath: Package::output.yml
                TemplateConfiguration: Package::configuration.json
              OutputArtifacts: [Name: ProdChangeSet]
            - Name: ApproveChangeSet
              RunOrder: 2
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration:
                NotificationArn: !Ref BuildApprovalSNS
                CustomData: !Sub "A new ${StackName} build is ready for deploy."
            - Name: ExecuteChangeSet
              RunOrder: 3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              InputArtifacts: [Name: ProdChangeSet]
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: ProdChangeSet
                StackName: !Ref StackName
  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      AuthenticationConfiguration:
        SecretToken: !Ref AWS::AccountId
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      Authentication: GITHUB_HMAC
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      Name: p5-replay-webhook
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true
  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/docker:17.09.0
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue p5ReplayCodeBuildRole
      Source:
        Type: CODEPIPELINE
        GitCloneDepth: 1
        BuildSpec: !Sub |
          version: 0.2
          env:
            variables:
              REPO: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${DockerRepo}
              REF_NAME: ${GitHubBranch}
              TEMPLATE_BUCKET: ${TemplateBucket}
              OUTPUT_TEMPLATE: output.yml
              STACK: ${StackName}
              STAGING_STACK: ${StackName}
              TEMPLATE_CONFIG: configuration.json
              STAGING_TEMPLATE_CONFIG: configuration-staging.json
          phases:
            install:
              commands:
                - apt-get update && apt-get install -y jq
            pre_build:
              commands:
                - docker version
                - $(aws ecr get-login --no-include-email)
            build:
              commands:
                - /bin/bash ./package.sh
            post_build:
              commands:
                - docker push $REPO
          artifacts:
            files:
              - output.yml
              - configuration.json
              - configuration-staging.json
  DockerRepo:
    Type: AWS::ECR::Repository
  BuildApprovalSNS:
    Type: AWS::SNS::Topic
