service: p5-replay-service

custom:
  destination_bucket: p5-replay-videos

provider:
  name: aws
  runtime: nodejs8.10
  profile: p5-replay # make sure to set up .awscredentials locally, following .awscredentials.sample as template
  timeout: 30 # for API gateway function must be <= 30
  stage: dev
  region: us-east-1
  memorySize: 3008
  environment:
    DESTINATION_BUCKET: ${self:custom.destination_bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:custom.destination_bucket}
            - "/*"

functions:
  runTest:
    handler: handler.runTest
    events:
      - http:
          path: runTest
          method: get
          cors: true
# Example lambda that triggers when an S3 object is created.
# Note that to use this, self:custom.source_bucket must be added to
# the iamRoleStatements above and also specified in the custom section
#  ffmpeg:
#    handler: handler.main
#    events:
#      - s3:
#          bucket: ${self:custom.source_bucket} # This will create the source bucket
#          event: s3:ObjectCreated:*

resources:
  Resources:
    S3BucketPermissions:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.destination_bucket}
        PolicyDocument:
          Statement:
            - Principal: "*"
              Action:
                - s3:GetObject
              Effect: Allow
              Sid: "PublicReadPermission"
              Resource:
                - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - ${self:custom.destination_bucket}
                    - "/*"
    UploadDestination:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.destination_bucket}
        AccessControl: PublicRead
        # TODO: verify that CORS requests work
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
